language: bash
services: docker

env:
  - VERSION=8-jre8
  - VERSION=8-jre7
  - VERSION=7-jre8
  - VERSION=7-jre7
  - VERSION=6-jre8
  - VERSION=6-jre7

install:
  - git clone https://github.com/docker-library/official-images.git ~/official-images

before_script:
  - docker pull isuper/java-oracle:jre_7
  - docker pull isuper/java-oracle:jre_8
  - env | sort
  - cd "$VERSION"
  - image="openweb/oracle-tomcat:$VERSION"

script:
  - docker build -t "$image" .
  - ~/official-images/test/run.sh "$image"
  - docker login -e="$DOCKER_EMAIL" -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
  - docker push "$image"

after_script:
  - docker images

# vim:set et ts=2 sw=2:
